name = "personal-website"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2023-08-20"

[[kv_namespaces]]
id = "0449bf9d3df946749c2add69a02c7407"
binding = "config"

[[r2_buckets]]
bucket_name = "blogs"
binding = "blogs"

# [[d1_databases]]
# binding = "auth"
# database_name = "auth"
# database_id = "7a6476cd-067f-4f50-ba6e-65cc3834e9a5"

[[env.production.kv_namespaces]]
id = "0449bf9d3df946749c2add69a02c7407"
binding = "config"
