name = "personal-website"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2023-08-20"

[[kv_namespaces]]
id = "0449bf9d3df946749c2add69a02c7407"
binding = "config"

[[r2_buckets]]
bucket_name = "blogs"
binding = "blogs"

[[d1_databases]]
binding = "db"
database_name = "personal-website"
database_id = "80b42eeb-f38f-48b1-b936-3683be4a8096"

[[env.production.kv_namespaces]]
id = "0449bf9d3df946749c2add69a02c7407"
binding = "config"

[[env.production.r2_buckets]]
bucket_name = "blogs"
binding = "blogs"

[[env.production.d1_databases]]
binding = "db"
database_name = "personal-website"
database_id = "80b42eeb-f38f-48b1-b936-3683be4a8096"
