name = "personal-website"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2023-08-20"

[[kv_namespaces]]
id = "0449bf9d3df946749c2add69a02c7407"
binding = "config"

[[r2_buckets]]
bucket_name = "blogs"
binding = "blogs"

[[d1_databases]]
binding = "comments"
database_name = "comments"
database_id = "dc0cc45d-3e92-451e-8d64-82cf1f9c5198"

[[env.production.kv_namespaces]]
id = "0449bf9d3df946749c2add69a02c7407"
binding = "config"

[[env.production.r2_buckets]]
bucket_name = "blogs"
binding = "blogs"

[[env.production.d1_databases]]
binding = "comments"
database_name = "comments"
database_id = "dc0cc45d-3e92-451e-8d64-82cf1f9c5198"
