name: Deploy Website

on:
  pull_request:
    branches: [default]
    types: [closed]

jobs:
  deploy:
    name: Deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Clone PR branch
        run: git clone -c core.autocrlf=false --depth=1 --branch=${{ github.base_ref }} https://github.com/${{ github.repository }}

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Deploy to live Firebase Hosting
        run: npx firebase-tools deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
