name: Deploy Website

on:
  pull_request:
    branches: [default]
    types: [closed]

jobs:
  deploy:
    name: Deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Clean directory
        run: rm -rf *

      - name: Clone public branch
        run: git clone -c core.autocrlf=false --depth=1 --branch=public https://${{ github.actor}}:${{ github.token }}@github.com/${{ github.repository }} public

      - name: Clone PR branch
        run: git clone -c core.autocrlf=false --depth=1 --branch=${{ github.base_ref }} https://github.com/${{ github.repository }} site

      - name: Install npm dependencies
        working-directory: site
        run: npm ci

      - name: Build
        working-directory: site
        run: npm run build

      - name: Copy public folder
        run: cp -rT site/public public

      - name: Configure git
        working-directory: public
        run: |
          git config --global user.email "${{ github.actor }}@nathanblair.rocks"
          git config --global user.name "${{ github.actor }}"

      - name: Commit changes
        working-directory: public
        run: |
          git status
          git add --all
          git commit -m "merge from branch ${{ github.head_ref }}"

      - name: Push changes
        working-directory: public
        run: git push origin public
